export const ok      = (res, data, status = 200) => res.status(status).json(data)
export const created = (res, data)               => res.status(201).json(data)
export const notFound  = (res, msg = 'No encontrado')     => res.status(404).json({ message: msg })
export const forbidden = (res, msg = 'Sin acceso')        => res.status(403).json({ message: msg })
export const badRequest= (res, msg = 'Datos inválidos')   => res.status(400).json({ message: msg })
export const unauth    = (res, msg = 'No autorizado')     => res.status(401).json({ message: msg })
